import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import { neckRegistry } from '../src/anatomy/neck-registry.mjs';
import { executeCoachAction, isValidCoachActionContract, resolveCoachQuery } from '../src/coach-c/structure-finder.mjs';
import { parseCoreSnapshot } from '../src/root-scm/domain-adapter.mjs';

const root = new URL('../', import.meta.url);
const html = await readFile(new URL('index.html', root), 'utf8');
const source = await readFile(new URL('src/coach-c/structure-finder.mjs', root), 'utf8');
const bridge = await readFile(new URL('assets/runtime/coach-query-root-adapter.js', root), 'utf8');
const runtime = await readFile(new URL('assets/runtime/coach-query-runtime.js', root), 'utf8');
const glb = await readFile(new URL('assets/anatomy/human-atlas/neck-muscles.glb', root));
const bundle = html.slice(html.indexOf('<!-- MOONBIT_CORE_START -->'), html.indexOf('<!-- MOONBIT_CORE_END -->')).match(/<script>\/\* Generated by npm run build from moonbit\/core\. \*\/\r?\n([\s\S]*)<\/script>/)?.[1];
const hash = (bytes) => createHash('sha256').update(bytes).digest('hex').toUpperCase();
const core = () => { const context = vm.createContext({}); context.globalThis = context; new vm.Script(bundle).runInContext(context); context.bodymate_domain_reset(); return context; };
const resolve = (context, text) => resolveCoachQuery(text, { core: context });
const snapshot = (context) => context.bodymate_core_snapshot();

test('browser query crosses the MoonBit resolver seam for exact Chinese and English names', () => {
  const context = core();
  for (const query of ['右侧胸锁乳突肌', 'right sternocleidomastoid']) {
    const outcome = resolve(context, query);
    assert.equal(outcome.classification, 'STRUCTURE_LOOKUP');
    assert.equal(outcome.resolution, 'EXACT');
    assert.deepEqual(outcome.action, { schemaVersion: 1, action: 'SELECT_STRUCTURE', structureId: 'bodymate.neck.sternocleidomastoid.right', confidence: 1, source: 'moonbit-domain' });
    assert.ok(isValidCoachActionContract(outcome.action));
  }
});

test('MoonBit normalizes sides and produces deterministic safe candidate groups', () => {
  const context = core();
  assert.equal(resolve(context, '左边头夹肌').action.structureId, 'bodymate.neck.splenius.capitis.left');
  assert.equal(resolve(context, 'r').resolution, 'NO_MATCH');
  const rightNeck = resolve(context, 'right neck side');
  assert.equal(rightNeck.resolution, 'AMBIGUOUS');
  assert.ok(rightNeck.candidates.every((candidate) => candidate.side === 'right'));
  assert.equal(resolve(context, 'SCM').structureSet.members.length, 2);
  assert.equal(resolve(context, '右侧斜角肌').structureSet.members.length, 3);
  assert.equal(resolve(context, 'scalene').structureSet.members.length, 6);
  assert.equal(resolve(context, '脖子侧面').resolution, 'AMBIGUOUS');
});

test('MoonBit rejects unsupported anatomy and health input without a domain mutation', () => {
  const context = core(), before = snapshot(context);
  const absent = resolve(context, '胸大肌');
  assert.equal(absent.resolution, 'NO_MATCH');
  assert.equal(absent.action, null);
  const health = resolve(context, '我脖子疼怎么办');
  assert.equal(health.classification, 'UNSUPPORTED_HEALTH_QUERY');
  assert.equal(health.action, null);
  assert.equal(snapshot(context), before);
  assert.match(health.message, /不提供诊断或治疗建议/);
});

test('accepted actions execute in MoonBit before the JavaScript presentation callback', () => {
  const context = core();
  const selected = resolve(context, '右侧胸锁乳突肌').action;
  let replies = [];
  assert.equal(executeCoachAction(selected, { core: context, onAccepted: (reply) => replies.push(reply) }), true);
  assert.equal(parseCoreSnapshot(replies[0]).selected, selected.structureId);
  assert.equal(executeCoachAction(resolve(context, '只看这块').action, { core: context, onAccepted: (reply) => replies.push(reply) }), true);
  assert.match(snapshot(context), /\|true\|false\|/);
  assert.equal(executeCoachAction(resolve(context, '显示周围').action, { core: context, onAccepted: (reply) => replies.push(reply) }), true);
  assert.match(snapshot(context), /\|false\|false\|/);
});

test('structure-set query does not mutate MoonBit until its accepted action is executed', () => {
  const context = core(), outcome = resolve(context, '右侧斜角肌'), before = snapshot(context);
  assert.equal(outcome.action.action, 'HIGHLIGHT_STRUCTURE_SET');
  assert.equal(snapshot(context), before);
  assert.equal(executeCoachAction(outcome.action, { core: context }), true);
  assert.match(context.bodymate_domain_snapshot_v3(), /structure_set\|bodymate\.neck\.set\.scalene\.right/);
});

test('ambiguous candidates do not mutate MoonBit until a user selection action is accepted', () => {
  const context = core(), outcome = resolve(context, '右边脖子'), before = snapshot(context);
  assert.equal(outcome.action.action, 'FIND_STRUCTURE');
  assert.equal(snapshot(context), before);
  const selected = { schemaVersion: 1, action: 'SELECT_STRUCTURE', structureId: outcome.candidates[0].structureId, confidence: 1, source: 'moonbit-domain' };
  assert.equal(executeCoachAction(selected, { core: context }), true);
  assert.equal(parseCoreSnapshot(snapshot(context)).selected, selected.structureId);
});

test('thin JS adapter has no resolver tables or action transition switch', () => {
  assert.match(source, /bodymate_domain_resolve_query_v2/);
  assert.match(source, /bodymate_domain_execute_action_v1/);
  assert.doesNotMatch(source, /searchHints|familyFor|healthResult|sideFor|candidate ranking/i);
  assert.doesNotMatch(source, /document\.|fetch\s*\(/);
  assert.match(bridge, /executeCoachAction/);
  assert.match(html, /assets\/runtime\/coach-query-runtime\.js/);
  assert.match(runtime, /BodyMateCoachQuery|bodymate_domain_resolve_query_v2/);
});

test('offline runtime, frozen Human Atlas GLB, and fourteen anatomy nodes remain unchanged', () => {
  assert.doesNotMatch(runtime, /\bfetch\s*\(|https?:\/\//);
  assert.equal(hash(glb), 'FA6A0CFDDF1DA59367EA8EB72DB77770A08A2F53D01097C2873ECFFD692F7065');
  assert.equal(neckRegistry.length, 14);
});
