import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import { neckRegistry } from '../src/anatomy/neck-registry.mjs';
import { executeCoachAction, isValidCoachActionContract, resolveCoachQuery } from '../src/coach-c/structure-finder.mjs';
import { registerRootEntries } from '../src/root-scm/domain-adapter.mjs';

const root = new URL('../', import.meta.url);
const html = await readFile(new URL('index.html', root), 'utf8');
const source = await readFile(new URL('src/coach-c/structure-finder.mjs', root), 'utf8');
const bridge = await readFile(new URL('assets/runtime/coach-query-root-adapter.js', root), 'utf8');
const runtime = await readFile(new URL('assets/runtime/coach-query-runtime.js', root), 'utf8');
const glb = await readFile(new URL('assets/anatomy/human-atlas/neck-muscles.glb', root));
const bundle = html.slice(html.indexOf('<!-- MOONBIT_CORE_START -->'), html.indexOf('<!-- MOONBIT_CORE_END -->')).match(/<script>\/\* Generated by npm run build from moonbit\/core\. \*\/\r?\n([\s\S]*)<\/script>/)?.[1];
const hash = (bytes) => createHash('sha256').update(bytes).digest('hex').toUpperCase();
const core = () => { const context = vm.createContext({}); context.globalThis = context; new vm.Script(bundle).runInContext(context); context.bodymate_core_clear(); registerRootEntries(context, neckRegistry); return context; };
const snapshot = (context) => context.bodymate_core_snapshot();
const controllerFor = (context) => ({
  selectStructure: (id) => String(context.bodymate_core_select_structure(id)).startsWith('ok|'),
  isolateSelected: () => String(context.bodymate_core_isolate_selected()).startsWith('ok|'),
  restoreContext: () => String(context.bodymate_core_restore_context()).startsWith('ok|'),
});

test('resolves exact Chinese and English names into the stable versioned action contract', () => {
  for (const query of ['右侧胸锁乳突肌', 'right sternocleidomastoid']) {
    const outcome = resolveCoachQuery(query);
    assert.equal(outcome.classification, 'STRUCTURE_LOOKUP');
    assert.equal(outcome.resolution, 'EXACT');
    assert.deepEqual(outcome.action, { schemaVersion: 1, action: 'SELECT_STRUCTURE', structureId: 'bodymate.neck.sternocleidomastoid.right', confidence: 1, source: 'local-resolver' });
    assert.ok(isValidCoachActionContract(outcome.action));
  }
});

test('normalizes left/right Chinese and English side terms without treating a side alone as a selection', () => {
  assert.equal(resolveCoachQuery('左边头夹肌').action.structureId, 'bodymate.neck.splenius.capitis.left');
  assert.equal(resolveCoachQuery('r').resolution, 'NO_MATCH');
  const outcome = resolveCoachQuery('right neck side');
  assert.equal(outcome.resolution, 'AMBIGUOUS');
  assert.ok(outcome.candidates.every((candidate) => candidate.side === 'right'));
});

test('keeps aliases and family names safely ambiguous when a side or exact subtype is absent', () => {
  const alias = resolveCoachQuery('SCM');
  assert.equal(alias.resolution, 'AMBIGUOUS');
  assert.equal(alias.candidates.length, 2);
  const rightScalenes = resolveCoachQuery('右侧斜角肌');
  assert.equal(rightScalenes.candidates.length, 3);
  assert.ok(rightScalenes.candidates.every((candidate) => candidate.side === 'right'));
  assert.equal(resolveCoachQuery('right scalenus anterior').action.structureId, 'bodymate.neck.scalene.anterior.right');
  assert.equal(resolveCoachQuery('scalene').candidates.length, 6);
});

test('returns candidates for broad locations and does not invent chest anatomy outside the frozen registry', () => {
  const broad = resolveCoachQuery('脖子侧面');
  assert.equal(broad.resolution, 'AMBIGUOUS');
  assert.ok(broad.candidates.length >= 3 && broad.candidates.length <= 6);
  const absent = resolveCoachQuery('胸大肌');
  assert.equal(absent.resolution, 'NO_MATCH');
  assert.equal(absent.action, null);
  assert.match(absent.message, /14/);
});

test('rejects health questions without changing structure state or emitting a medical action', () => {
  const context = core(), before = snapshot(context), outcome = resolveCoachQuery('我脖子疼怎么办');
  assert.equal(outcome.classification, 'UNSUPPORTED_HEALTH_QUERY');
  assert.equal(outcome.action, null);
  assert.equal(snapshot(context), before);
  assert.match(outcome.message, /不提供诊断或治疗建议/);
});

test('maps isolate and restore language to only the approved MoonBit actions', () => {
  assert.equal(resolveCoachQuery('只看这块').action.action, 'ISOLATE_SELECTED');
  assert.equal(resolveCoachQuery('显示周围').action.action, 'RESTORE_CONTEXT');
  assert.equal(isValidCoachActionContract({ schemaVersion: 1, action: 'DIAGNOSE', confidence: 1, source: 'local-resolver' }), false);
});

test('candidate selection goes through the action executor and MoonBit rather than mutating a resolver snapshot', () => {
  const context = core(), outcome = resolveCoachQuery('右侧斜角肌'), selected = outcome.candidates[0].structureId;
  const before = snapshot(context);
  assert.equal(outcome.action.action, 'FIND_STRUCTURE');
  assert.equal(snapshot(context), before, 'an ambiguous resolver result must not select a mesh');
  const selectedAction = { schemaVersion: 1, action: 'SELECT_STRUCTURE', structureId: selected, confidence: 1, source: 'local-resolver' };
  assert.equal(executeCoachAction(selectedAction, controllerFor(context)), true);
  assert.match(snapshot(context), new RegExp(`^ok\\|neck\\|${selected.replace(/[.]/g, '\\.')}`));
});

test('isolate and restore execute through MoonBit and preserve its validated snapshot facts', () => {
  const context = core(), select = resolveCoachQuery('右侧胸锁乳突肌').action;
  assert.equal(executeCoachAction(select, controllerFor(context)), true);
  assert.equal(executeCoachAction(resolveCoachQuery('只看这块').action, controllerFor(context)), true);
  assert.match(snapshot(context), /\|true\|false\|/);
  assert.equal(executeCoachAction(resolveCoachQuery('显示周围').action, controllerFor(context)), true);
  assert.match(snapshot(context), /\|false\|false\|/);
});

test('query presentation is isolated from domain facts and uses the spatial Coach C bubble plus compact candidate buttons', () => {
  assert.match(source, /resolveCoachQuery/);
  assert.doesNotMatch(source, /document\.|selected\s*=|fetch\s*\(/);
  assert.match(bridge, /coach-query-candidates/);
  assert.match(bridge, /__rootScmQueryFeedback/);
  assert.match(bridge, /executeCoachAction/);
  assert.match(html, /assets\/runtime\/coach-query-runtime\.js/);
  assert.match(html, /assets\/runtime\/coach-query-root-adapter\.js/);
  assert.match(runtime, /BodyMateCoachQuery|local-resolver/);
});

test('offline runtime, frozen Human Atlas GLB, and 14 anatomy nodes remain unchanged', () => {
  assert.doesNotMatch(runtime, /\bfetch\s*\(|https?:\/\//);
  assert.equal(hash(glb), 'FA6A0CFDDF1DA59367EA8EB72DB77770A08A2F53D01097C2873ECFFD692F7065');
  assert.equal(neckRegistry.length, 14);
});
