import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const start = '<!-- MOONBIT_CORE_START -->';
const end = '<!-- MOONBIT_CORE_END -->';
const embedded = html.slice(html.indexOf(start) + start.length, html.indexOf(end));
const bundle = embedded.match(/<script>\/\* Generated by npm run build from moonbit\/core\. \*\/\n([\s\S]*)<\/script>/)?.[1];

function loadCore() {
  assert.ok(bundle, 'the tested MoonBit IIFE must be embedded in index.html');
  const context = vm.createContext({});
  context.globalThis = context;
  new vm.Script(bundle, { filename: 'embedded-moonbit-core.js' }).runInContext(context);
  return context;
}

test('embedded MoonBit IIFE exports and executes the interaction contract', () => {
  const core = loadCore();
  for (const name of ['bodymate_core_clear', 'bodymate_core_register', 'bodymate_core_select_region', 'bodymate_core_select_region_layer', 'bodymate_core_select_structure', 'bodymate_core_set_layer', 'bodymate_core_isolate_selected', 'bodymate_core_restore_context', 'bodymate_core_reset_overview', 'bodymate_core_snapshot']) {
    assert.equal(typeof core[name], 'function', `missing ${name}`);
  }
  assert.match(core.bodymate_core_clear(), /^ok\|/);
  assert.equal(core.bodymate_core_register('scm_r', '右侧胸锁乳突肌', 'neck', 'muscle', true), 'ok|registered');
  assert.equal(core.bodymate_core_register('fascia_neck', '颈肩筋膜', 'neck', 'fascia', true), 'ok|registered');
  assert.equal(core.bodymate_core_register('pec_r', '右侧胸大肌', 'chest', 'muscle', true), 'ok|registered');
  assert.equal(core.bodymate_core_select_region('neck'), 'ok|neck|scm_r|muscle|false|false|1');
  assert.equal(core.bodymate_core_set_layer('fascia'), 'ok|neck|fascia_neck|fascia|false|false|2');
  const before = core.bodymate_core_snapshot();
  assert.equal(core.bodymate_core_select_region_layer('chest', 'fascia'), 'error|uncovered_region_or_layer');
  assert.equal(core.bodymate_core_snapshot(), before, 'failed atomic selection must preserve the snapshot');
  assert.equal(core.bodymate_core_select_region_layer('chest', 'muscle'), 'ok|chest|pec_r|muscle|false|false|3');
  assert.equal(core.bodymate_core_isolate_selected(), 'ok|chest|pec_r|muscle|true|false|4');
  assert.equal(core.bodymate_core_restore_context(), 'ok|chest|pec_r|muscle|false|false|5');
  assert.equal(core.bodymate_core_select_structure('missing'), 'error|unknown_structure');
  assert.equal(core.bodymate_core_snapshot(), 'ok|chest|pec_r|muscle|false|false|5');
});
