import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import { originalScmMeshNames, originalScmRegistry, entryForOriginalMeshName } from '../prototype/original-scm/original-scm-registry.mjs';
import { focusPlanFromBounds, parseCoreSnapshot, rendererVisibilityForSnapshot } from '../prototype/original-scm/original-scm-domain.mjs';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const embedded = html.slice(html.indexOf('<!-- MOONBIT_CORE_START -->'), html.indexOf('<!-- MOONBIT_CORE_END -->'));
const bundle = embedded.match(/<script>\/\* Generated by npm run build from moonbit\/core\. \*\/\n([\s\S]*)<\/script>/)?.[1];
function core() { const context = vm.createContext({}); context.globalThis = context; new vm.Script(bundle).runInContext(context); return context; }

test('original SCM registry maps every generated mesh to one stable BodyMate ID', () => {
  assert.equal(originalScmRegistry.length, 1);
  assert.equal(originalScmMeshNames.length, 16);
  assert.equal(new Set(originalScmMeshNames).size, 16);
  assert.equal(entryForOriginalMeshName('procedural-scm-surface')?.structureId, 'bodymate.neck.sternocleidomastoid.right');
  assert.equal(entryForOriginalMeshName('unknown-renderer-object'), null);
});

test('generated mesh selection reaches MoonBit and unknown renderer names do not alter state', () => {
  const runtime = core();
  runtime.bodymate_core_clear();
  const entry = originalScmRegistry[0];
  assert.equal(runtime.bodymate_core_register(entry.structureId, entry.displayNameZh, entry.region, entry.layer, true), 'ok|registered');
  const before = parseCoreSnapshot(runtime.bodymate_core_snapshot());
  assert.equal(entryForOriginalMeshName('not-an-scm-part'), null);
  assert.deepEqual(parseCoreSnapshot(runtime.bodymate_core_snapshot()), before);
  const selected = parseCoreSnapshot(runtime.bodymate_core_select_structure(entryForOriginalMeshName('procedural-scm-fiber-08').structureId));
  assert.equal(selected.selected, entry.structureId);
  assert.equal(selected.overview, false);
});

test('isolate restore visibility and bounds focus follow the validated snapshot', () => {
  const id = originalScmRegistry[0].structureId;
  assert.deepEqual(rendererVisibilityForSnapshot({ selected: id, isolated: true }, id), { structureVisible: true, contextVisible: false });
  assert.deepEqual(rendererVisibilityForSnapshot({ selected: id, isolated: false }, id), { structureVisible: true, contextVisible: true });
  const plan = focusPlanFromBounds({ min: { x: -0.2, y: -1.1, z: 0.1 }, max: { x: 0.7, y: 1.4, z: 0.5 } });
  assert.deepEqual(plan.target, { x: 0.24999999999999997, y: 0.1499999999999999, z: 0.3 });
  assert.ok(plan.distance >= 1.25);
});
