import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import { NodeIO } from '@gltf-transform/core';
import { axisTransform, structureId } from '../scripts/anatomy-build-scm.mjs';
import { licenseSha256, licenseUrl } from '../scripts/anatomy-source.mjs';
import { entryForPublicNode } from '../prototype/public-scm/public-registry.mjs';
import { focusPlanFromBounds, parseCoreSnapshot } from '../prototype/public-scm/public-domain.mjs';

const root = new URL('../', import.meta.url);
const decision = JSON.parse(await readFile(new URL('docs/anatomy-asset-candidates.json', root), 'utf8'));
const manifest = JSON.parse(await readFile(new URL('assets/anatomy/open-anatomy/manifest.json', root), 'utf8'));
const glb = await readFile(new URL('assets/anatomy/open-anatomy/scm-right.glb', root));
const html = await readFile(new URL('index.html', root), 'utf8');
const embedded = html.slice(html.indexOf('<!-- MOONBIT_CORE_START -->'), html.indexOf('<!-- MOONBIT_CORE_END -->'));
const bundle = embedded.match(/<script>\/\* Generated by npm run build from moonbit\/core\. \*\/\r?\n([\s\S]*)<\/script>/)?.[1];
const mandatoryLicensePreface = 'All or portions of this licensed product (such portions are the "Software") have been obtained under license from The Brigham and Women\'s Hospital, Inc. and are subject to the following terms and conditions:';
function hash(bytes) { return createHash('sha256').update(bytes).digest('hex').toUpperCase(); }
function core() { const context = vm.createContext({}); context.globalThis = context; new vm.Script(bundle).runInContext(context); return context; }

test('pinned public SCM metadata agrees with the Stage 2B decision', () => {
  const approved = decision.approvedPublicAssets.find((asset) => asset.stableStructureId === structureId);
  assert.equal(manifest.sourceArchiveSha256, decision.approvedArchive.sha256);
  assert.equal(manifest.sourceSha256, approved.meshComplexity.sha256);
  assert.equal(manifest.sourceFile, approved.exactFile);
  assert.equal(manifest.sourceStructureId, approved.sourceStructureId);
  assert.equal(manifest.vertexCount, approved.meshComplexity.vertices);
  assert.equal(manifest.triangleCount, approved.meshComplexity.triangles);
});

test('public anatomy asset has required legal, provenance, and output-hash gates', async () => {
  const [license, notice, upstream] = await Promise.all(['LICENSE.md', 'NOTICE.md', 'UPSTREAM_ARCHIVE_LICENSE.md'].map((file) => readFile(new URL(`assets/anatomy/open-anatomy/${file}`, root), 'utf8')));
  assert.equal(hash(glb), manifest.outputSha256);
  assert.match(license, /3D Slicer Contribution and Software License Agreement/);
  assert.match(upstream, /This atlas is released under the terms/);
  assert.ok(notice.includes(mandatoryLicensePreface), 'NOTICE.md must preserve the full Part B 1(b) mandatory preface with ASCII quotes.');
  assert.match(notice, /Marianna Jakab; Ron Kikinis/);
  assert.equal(manifest.licensePath, 'assets/anatomy/open-anatomy/LICENSE.md');
  assert.equal(manifest.noticePath, 'assets/anatomy/open-anatomy/NOTICE.md');
  assert.equal(licenseUrl, 'https://raw.githubusercontent.com/Slicer/Slicer/68ff0ae7114e4378322740f117643d7513a71110/License.txt');
  assert.equal(licenseSha256, '03FC5CD907E5C2004CE199D66318D32A08FA2DE2B5B28BEE184EDDA6307D0B86');
});

test('committed GLB is a finite single-SCM asset with the documented transform', async () => {
  const document = await new NodeIO().readBinary(new Uint8Array(glb));
  const nodes = document.getRoot().listNodes(), meshes = document.getRoot().listMeshes();
  assert.equal(nodes.length, 1); assert.equal(meshes.length, 1);
  assert.equal(nodes[0].getName(), structureId); assert.equal(meshes[0].getName(), structureId);
  assert.equal(nodes[0].getExtras().structureId, structureId); assert.equal(meshes[0].getExtras().sourceSha256, manifest.sourceSha256);
  assert.ok(Array.from(nodes[0].getMatrix()).every((value, index) => Math.abs(value - axisTransform[index]) < 1e-12)); assert.deepEqual(manifest.axisTransform, axisTransform);
  const primitive = meshes[0].listPrimitives()[0], positions = primitive.getAttribute('POSITION').getArray(), indices = primitive.getIndices().getArray();
  assert.equal(positions.length / 3, manifest.vertexCount); assert.equal(indices.length / 3, manifest.triangleCount);
  assert.ok([...positions].every(Number.isFinite)); assert.ok([...indices].every((index) => index >= 0 && index < manifest.vertexCount));
  const range = manifest.boundingBox.sourceLpsMillimeters.max.map((value, axis) => value - manifest.boundingBox.sourceLpsMillimeters.min[axis]); assert.ok(range.every((value) => value > 0));
});

test('public GLB registry mapping selects through MoonBit and unknown names are inert', () => {
  const entry = entryForPublicNode(structureId); assert.equal(entry?.structureId, structureId); assert.equal(entryForPublicNode('Mesh_0'), null);
  const runtime = core(); runtime.bodymate_core_clear(); assert.equal(runtime.bodymate_core_register(entry.structureId, entry.displayNameZh, entry.region, entry.layer, true), 'ok|registered');
  const selected = parseCoreSnapshot(runtime.bodymate_core_select_structure(entry.structureId)); assert.equal(selected.selected, structureId);
  assert.equal(entryForPublicNode('unknown-structure'), null); assert.deepEqual(parseCoreSnapshot(runtime.bodymate_core_snapshot()), selected);
});

test('public viewer focus plan is derived from committed GLB bounds', () => {
  const bounds = manifest.boundingBox.outputGltfMeters;
  const plan = focusPlanFromBounds({ min: { x: bounds.min[0], y: bounds.min[1], z: bounds.min[2] }, max: { x: bounds.max[0], y: bounds.max[1], z: bounds.max[2] } });
  assert.ok(Number.isFinite(plan.distance) && plan.distance > 0);
  assert.notDeepEqual(plan.target, { x: 0, y: 0, z: 0 });
});
