import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import { anatomyRegistry, entryForMeshName, registryMeshNames } from '../prototype/real-neck/anatomy-registry.mjs';
import { focusPlanFromBounds, parseCoreSnapshot, visibilityForSnapshot } from '../prototype/real-neck/spike-domain.mjs';

const html = await readFile(new URL('../index.html', import.meta.url), 'utf8');
const embedded = html.slice(html.indexOf('<!-- MOONBIT_CORE_START -->'), html.indexOf('<!-- MOONBIT_CORE_END -->'));
const bundle = embedded.match(/<script>\/\* Generated by npm run build from moonbit\/core\. \*\/\n([\s\S]*)<\/script>/)?.[1];
function core(){const context=vm.createContext({});context.globalThis=context;new vm.Script(bundle).runInContext(context);return context;}

test('registry maps each stable ID to a unique BodyParts3D mesh name', () => {
  assert.equal(anatomyRegistry.length, 2);assert.equal(registryMeshNames().size, 2);assert.equal(entryForMeshName('FJ1595').structureId, 'bodymate.neck.sternocleidomastoid.right');assert.equal(entryForMeshName('unknown'), null);
});
test('real mesh mapping selects through MoonBit and ignores unknown mesh names', () => {
  const runtime=core();runtime.bodymate_core_clear();for(const entry of anatomyRegistry)assert.equal(runtime.bodymate_core_register(entry.structureId,entry.displayNameZh,entry.region,entry.layer,entry.structureId.endsWith('sternocleidomastoid.right')),'ok|registered');
  const before=parseCoreSnapshot(runtime.bodymate_core_select_structure(entryForMeshName('FJ1595').structureId));assert.equal(entryForMeshName('not-a-source-mesh'),null);assert.deepEqual(parseCoreSnapshot(runtime.bodymate_core_snapshot()),before);assert.equal(before.selected,'bodymate.neck.sternocleidomastoid.right');
});
test('isolate, restore, and bounds focus plans stay consistent with renderer data', () => {
  const selected={region:'neck',selected:anatomyRegistry[0].structureId,layer:'muscle',isolated:true,overview:false,revision:5};const isolated=visibilityForSnapshot(anatomyRegistry,selected);assert.equal(isolated.get(anatomyRegistry[0].structureId),true);assert.equal(isolated.get(anatomyRegistry[1].structureId),false);
  const restored=visibilityForSnapshot(anatomyRegistry,{...selected,isolated:false});assert.equal([...restored.values()].every(Boolean),true);const plan=focusPlanFromBounds({min:{x:-2,y:1,z:4},max:{x:4,y:5,z:8}});assert.deepEqual(plan.target,{x:1,y:3,z:6});assert.ok(plan.distance>0);assert.notEqual(plan.distance,13.5);
});
