import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFile } from 'node:fs/promises';
import test from 'node:test';
import vm from 'node:vm';
import { canonicalScmId, entryForPresentationId, legacyPresentationIdForCoreId } from '../src/root-scm/registry.mjs';
import { focusPlanFromBounds, registerRootEntries, selectPresentationStructure } from '../src/root-scm/domain-adapter.mjs';

const root = new URL('../', import.meta.url);
const html = await readFile(new URL('index.html', root), 'utf8');
const manifest = JSON.parse(await readFile(new URL('assets/anatomy/open-anatomy/manifest.json', root), 'utf8'));
const glb = await readFile(new URL('assets/anatomy/open-anatomy/scm-right.glb', root));
const runtime = await readFile(new URL('assets/runtime/root-scm-runtime.js', root), 'utf8');
const start = '<!-- MOONBIT_CORE_START -->';
const end = '<!-- MOONBIT_CORE_END -->';
const embedded = html.slice(html.indexOf(start) + start.length, html.indexOf(end));
const bundle = embedded.match(/<script>\/\* Generated by npm run build from moonbit\/core\. \*\/\n([\s\S]*)<\/script>/)?.[1];
const hash = (bytes) => createHash('sha256').update(bytes).digest('hex').toUpperCase();

function core() { const context = vm.createContext({}); context.globalThis = context; new vm.Script(bundle).runInContext(context); return context; }
function snapshot(runtime) { return runtime.bodymate_core_snapshot(); }

test('all SCM presentation entrances resolve to one canonical domain ID', () => {
  assert.equal(canonicalScmId, 'bodymate.neck.sternocleidomastoid.right');
  for (const id of ['scm_r', canonicalScmId]) assert.equal(entryForPresentationId(id)?.structureId, canonicalScmId);
  assert.equal(legacyPresentationIdForCoreId(canonicalScmId), 'scm_r');
  assert.equal(entryForPresentationId('unknown-legacy-node'), null);
});

test('root domain adapter registers the canonical SCM once and leaves unknown input inert', () => {
  const runtime = core();
  runtime.bodymate_core_clear();
  registerRootEntries(runtime, [
    { presentationId: 'scm_r', structureId: canonicalScmId, displayNameZh: '右侧胸锁乳突肌', region: 'neck', layer: 'muscle', isDefault: true },
    { presentationId: 'pec_r', structureId: 'pec_r', displayNameZh: '右侧胸大肌', region: 'chest', layer: 'muscle', isDefault: true },
  ]);
  assert.equal(runtime.bodymate_core_register('scm_r', '重复 ID', 'neck', 'muscle', false), 'ok|registered');
  const selected = selectPresentationStructure(runtime, 'scm_r');
  assert.equal(selected?.selected, canonicalScmId);
  const before = snapshot(runtime);
  assert.equal(selectPresentationStructure(runtime, 'unknown-legacy-node'), null);
  assert.equal(snapshot(runtime), before);
});

test('bounds focus uses real SCM bounds rather than a hard-coded camera target', () => {
  const bounds = manifest.boundingBox.outputGltfMeters;
  const plan = focusPlanFromBounds({ min: { x: bounds.min[0], y: bounds.min[1], z: bounds.min[2] }, max: { x: bounds.max[0], y: bounds.max[1], z: bounds.max[2] } });
  assert.ok(plan.distance > 0 && Number.isFinite(plan.distance));
  assert.notDeepEqual(plan.target, { x: 0, y: 0, z: 0 });
  assert.equal(plan.direction.length, 3);
});

test('root retains legacy views but has an explicit real-SCM detail path and attribution entry', async () => {
  const adapter = await readFile(new URL('assets/runtime/root-scm-root-adapter.js', root), 'utf8');
  for (const id of ['nav-canvas', 'detail-canvas', 'orb-canvas']) assert.match(html, new RegExp(`id=["']${id}["']`));
  assert.match(html, /assets\/runtime\/root-scm-runtime\.js/);
  assert.match(html, /root-scm-root-adapter\.js/);
  assert.match(adapter, /root-scm-canvas/);
  assert.match(adapter, /真实 SCM 资源未能初始化/);
  assert.match(adapter, /Open Anatomy \/ SPL Head and Neck Atlas/);
  assert.match(adapter, /assets\/anatomy\/open-anatomy\/NOTICE\.md/);
});

test('generated classic runtime is derived from the canonical GLB and has no external anatomy request', async () => {
  const source = await readFile(new URL('src/root-scm/runtime-entry.mjs', root), 'utf8');
  assert.equal(hash(glb), manifest.outputSha256);
  assert.match(runtime, /GENERATED DERIVED RUNTIME REPRESENTATION/);
  assert.match(runtime, new RegExp(manifest.outputSha256));
  assert.match(runtime, /BodyMateRootScmRuntime/);
  assert.doesNotMatch(source, /\bfetch\s*\(/);
  assert.doesNotMatch(source, /loadAsync\s*\(/);
});

test('canonical public source retains provenance gates for root integration', async () => {
  const [license, notice] = await Promise.all(['LICENSE.md', 'NOTICE.md'].map((file) => readFile(new URL(`assets/anatomy/open-anatomy/${file}`, root), 'utf8')));
  assert.match(license, /3D Slicer Contribution and Software License Agreement/);
  assert.match(notice, /Marianna Jakab; Ron Kikinis/);
  assert.equal(manifest.structureId, canonicalScmId);
});
