import { createServer } from 'node:http';
import { fileURLToPath } from 'node:url';
import { configFromEnv, createAiBridge, createOpenAiCompatibleProvider, isAllowedBrowserOrigin } from './bridge.mjs';

const readJson = (request) => new Promise((resolve, reject) => { let body = ''; request.on('data', (chunk) => { body += chunk; if (body.length > 8192) reject(Error('body_too_large')); }); request.on('end', () => { try { resolve(JSON.parse(body || '{}')); } catch { reject(Error('invalid_json')); } }); request.on('error', reject); });
const send = (response, status, body, origin) => { const headers = { 'content-type': 'application/json; charset=utf-8', 'cache-control': 'no-store' }; if (isAllowedBrowserOrigin(origin)) { headers['access-control-allow-origin'] = origin; headers.vary = 'Origin'; } response.writeHead(status, headers); response.end(JSON.stringify(body)); };
export function createBridgeServer(bridge) { return createServer(async (request, response) => { const origin = request.headers.origin; if (request.method === 'OPTIONS' && request.url === '/api/coach/resolve') { if (!isAllowedBrowserOrigin(origin)) return send(response, 403, { error: 'origin_not_allowed' }); response.writeHead(204, { 'access-control-allow-origin': origin, 'access-control-allow-methods': 'POST, OPTIONS', 'access-control-allow-headers': 'content-type', vary: 'Origin' }); return response.end(); } if (request.method !== 'POST' || request.url !== '/api/coach/resolve') return send(response, 404, { error: 'not_found' }, origin); if (origin && !isAllowedBrowserOrigin(origin)) return send(response, 403, { error: 'origin_not_allowed' }); try { const reply = await bridge.resolve(await readJson(request)); return send(response, reply.status, reply.body, origin); } catch { return send(response, 400, { error: 'invalid_request' }, origin); } }); }
export function startFromEnv(env = process.env) { const config = configFromEnv(env); if (!config) throw Error('BODYMATE_AI_BASE_URL, BODYMATE_AI_API_KEY, and BODYMATE_AI_MODEL must be set in the secure bridge environment.'); const bridge = createAiBridge({ provider: createOpenAiCompatibleProvider(config), timeoutMs: config.timeoutMs }); const port = Number(env.BODYMATE_AI_BRIDGE_PORT) || 8787; const server = createBridgeServer(bridge); server.listen(port, '127.0.0.1', () => console.log(`BodyMate AI bridge listening on http://127.0.0.1:${port}`)); return server; }
if (typeof process !== 'undefined' && process.argv[1] === fileURLToPath(import.meta.url)) startFromEnv();
