import * as THREE from 'three';
import { OrbitControls } from 'three/addons/controls/OrbitControls.js';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';
import { parseCoreSnapshot, focusPlanFromBounds } from './public-domain.mjs';
import { entryForPublicNode, publicScmRegistry } from './public-registry.mjs';

const canvas=document.querySelector('#scene'),status=document.querySelector('#status'),selection=document.querySelector('#selection'),structureId=document.querySelector('#structure-id'),revision=document.querySelector('#revision'),select=document.querySelector('#select');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(33,1,.01,20),controls=new OrbitControls(camera,canvas),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();scene.add(new THREE.HemisphereLight(0xfafdff,0x91a8c1,2.3));const key=new THREE.DirectionalLight(0xffffff,2.5);key.position.set(2,3,2);scene.add(key);const fill=new THREE.DirectionalLight(0x9ecbff,.55);fill.position.set(-2,1,2);scene.add(fill);let mesh,snapshot;
function resize(){const box=canvas.getBoundingClientRect();renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvas);resize();(function render(){controls.update();renderer.render(scene,camera);requestAnimationFrame(render)})();
function coreCall(name,...args){const fn=globalThis[name];if(typeof fn!=='function')throw Error(`MoonBit core missing: ${name}`);const next=parseCoreSnapshot(fn(...args));if(!next)throw Error(`MoonBit rejected ${name}`);snapshot=next;return next}
function initialiseCore(){if(typeof globalThis.bodymate_core_clear!=='function')throw Error('MoonBit build missing; run npm run build.');globalThis.bodymate_core_clear();for(const entry of publicScmRegistry){const reply=globalThis.bodymate_core_register(entry.structureId,entry.displayNameZh,entry.region,entry.layer,true);if(reply!=='ok|registered')throw Error(`MoonBit registration failed: ${reply}`)}}
function paint(active){const material=mesh.material;material.color.set(active?0x83b9f4:0xe7edf1);material.emissive.set(active?0x163d6d:0x000000);material.emissiveIntensity=active?.16:0;material.roughness=.62;material.metalness=.02;material.needsUpdate=true}
function focus(){const box=new THREE.Box3().setFromObject(mesh),plan=focusPlanFromBounds(box),direction=new THREE.Vector3(1,.48,1).normalize();controls.target.set(plan.target.x,plan.target.y,plan.target.z);camera.position.copy(controls.target).addScaledVector(direction,plan.distance);controls.update()}
function applySnapshot(){const entry=publicScmRegistry.find((candidate)=>candidate.structureId===snapshot.selected);paint(Boolean(entry));selection.textContent=entry?.displayNameZh??'未选择';structureId.textContent=snapshot.selected||'—';revision.textContent=String(snapshot.revision)}
function entryForObject(object){for(let current=object;current;current=current.parent){const entry=entryForPublicNode(current.name)||publicScmRegistry.find((candidate)=>candidate.structureId===current.userData?.structureId);if(entry)return entry}return null}
function selectScm(){const entry=entryForObject(mesh);if(!entry)throw Error('Loaded GLB node cannot map through the public Anatomy Registry.');coreCall('bodymate_core_select_structure',entry.structureId);applySnapshot();focus();status.textContent='已通过 Registry → MoonBit → validated snapshot 选择 SCM'}
function findMappedMesh(root){let found=null;root.traverse((node)=>{if(node.isMesh&&entryForObject(node)){found=node;node.material=node.material.clone()}});return found}
canvas.addEventListener('pointerup',(event)=>{if(event.movementX||event.movementY)return;const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=mesh&&raycaster.intersectObject(mesh,false)[0];if(hit)selectScm()});select.onclick=selectScm;
try{initialiseCore();const gltf=await new GLTFLoader().loadAsync('../../assets/anatomy/open-anatomy/scm-right.glb');scene.add(gltf.scene);mesh=findMappedMesh(gltf.scene);if(!mesh)throw Error('Committed GLB is missing its stable SCM mesh name.');paint(false);focus();status.textContent='已加载仓库内公开 SCM GLB · 点击结构验证 MoonBit 链路'}catch(error){console.error(error);status.textContent=`公开 SCM 验证失败：${error.message}`}
