import * as THREE from '../../node_modules/three/build/three.module.js';
import { OBJLoader } from '../../node_modules/three/examples/jsm/loaders/OBJLoader.js';
import { OrbitControls } from '../../node_modules/three/examples/jsm/controls/OrbitControls.js';
import '../../_build/js/debug/build/core/core.js';
import { anatomyRegistry, entryForMeshName } from './anatomy-registry.mjs';
import { focusPlanFromBounds, parseCoreSnapshot, visibilityForSnapshot } from './spike-domain.mjs';

const canvas=document.querySelector('#scene'),status=document.querySelector('#status'),selection=document.querySelector('#selection'),source=document.querySelector('#source'),revision=document.querySelector('#revision'),visibility=document.querySelector('#visibility'),isolate=document.querySelector('#isolate'),restore=document.querySelector('#restore'),reset=document.querySelector('#reset');
const renderer=new THREE.WebGLRenderer({canvas,antialias:true,alpha:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(33,1,.01,50),controls=new OrbitControls(camera,canvas),group=new THREE.Group(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2(),meshForStructure=new Map();
camera.position.set(2.3,1.8,3.4);controls.enableDamping=true;controls.target.set(0,.8,0);scene.add(new THREE.HemisphereLight(0xf9fcff,0x8fa5bd,2.2));const key=new THREE.DirectionalLight(0xffffff,2.4);key.position.set(3,5,4);scene.add(key);const fill=new THREE.DirectionalLight(0xa9d4ff,.7);fill.position.set(-4,1,2);scene.add(fill);scene.add(group);
let snapshot=null,selectedMesh=null;
function resize(){const box=canvas.getBoundingClientRect();renderer.setSize(box.width,box.height,false);camera.aspect=box.width/box.height;camera.updateProjectionMatrix()}new ResizeObserver(resize).observe(canvas);resize();function render(){controls.update();renderer.render(scene,camera);requestAnimationFrame(render)}render();
function coreCall(name,...args){const fn=globalThis[name];if(typeof fn!=='function')throw Error(`MoonBit core missing: ${name}`);const next=parseCoreSnapshot(fn(...args));if(!next)throw Error(`Core rejected or returned malformed snapshot: ${name}`);snapshot=next;return next}
function initialiseCore(){if(typeof globalThis.bodymate_core_clear!=='function')throw Error('MoonBit build is missing; run npm run build first.');globalThis.bodymate_core_clear();for(const entry of anatomyRegistry){const reply=globalThis.bodymate_core_register(entry.structureId,entry.displayNameZh,entry.region,entry.layer,entry.structureId.endsWith('sternocleidomastoid.right'));if(reply!=='ok|registered')throw Error(`Core registration failed: ${reply}`)}coreCall('bodymate_core_select_structure',anatomyRegistry[0].structureId)}
function styleMesh(mesh,active){mesh.material.color.set(active?0x83b9f4:0xe7edf1);mesh.material.emissive.set(active?0x173f70:0x000000);mesh.material.emissiveIntensity=active?.18:0;mesh.material.opacity=active?.98:.92;mesh.material.transparent=true}
function focusStructure(mesh){const box=new THREE.Box3().setFromObject(mesh),plan=focusPlanFromBounds(box),direction=new THREE.Vector3(1,.45,1).normalize();controls.target.set(plan.target.x,plan.target.y,plan.target.z);camera.position.copy(controls.target).addScaledVector(direction,plan.distance);controls.update()}
function applySnapshot(){const map=visibilityForSnapshot(anatomyRegistry,snapshot);for(const entry of anatomyRegistry){const mesh=meshForStructure.get(entry.structureId);mesh.visible=map.get(entry.structureId);styleMesh(mesh,entry.structureId===snapshot.selected)}selectedMesh=meshForStructure.get(snapshot.selected);selection.textContent=anatomyRegistry.find(x=>x.structureId===snapshot.selected).displayNameZh;revision.textContent=String(snapshot.revision);visibility.textContent=[...map].filter(([,shown])=>shown).length+' / '+anatomyRegistry.length+' meshes visible';isolate.disabled=snapshot.isolated;restore.disabled=!snapshot.isolated;reset.disabled=false}
function selectEntry(entry){coreCall('bodymate_core_select_structure',entry.structureId);applySnapshot();focusStructure(meshForStructure.get(entry.structureId))}
function loadEntry(entry){return new Promise((resolve,reject)=>new OBJLoader().load(`./local-assets/${entry.meshNames[0]}.obj`,object=>{let mesh;object.traverse(node=>{if(node.isMesh){mesh=node;node.geometry.computeVertexNormals();node.material=new THREE.MeshStandardMaterial({roughness:.62,metalness:.03,side:THREE.DoubleSide});node.name=entry.meshNames[0]}});if(!mesh)return reject(Error(`No mesh in ${entry.meshNames[0]}.obj`));object.scale.setScalar(.012);group.add(object);meshForStructure.set(entry.structureId,mesh);resolve()},undefined,reject))}
canvas.addEventListener('pointerup',event=>{if(event.movementX||event.movementY)return;const rect=canvas.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects([...meshForStructure.values()],false)[0];const entry=hit&&entryForMeshName(hit.object.name);if(entry)selectEntry(entry)});
isolate.onclick=()=>{coreCall('bodymate_core_isolate_selected');applySnapshot()};restore.onclick=()=>{coreCall('bodymate_core_restore_context');applySnapshot()};reset.onclick=()=>focusStructure(selectedMesh);
try{initialiseCore();await Promise.all(anatomyRegistry.map(loadEntry));group.position.sub(new THREE.Box3().setFromObject(group).getCenter(new THREE.Vector3()));applySnapshot();focusStructure(selectedMesh);source.textContent='BodyParts3D Release 4.0 · FMA / BP / FJ provenance is recorded in the registry.';status.textContent='本地真实网格已加载 · 点击结构验证完整链路'}catch(error){console.error(error);status.textContent='未完成本地资产验证';source.textContent=error.message+' See prototype/real-neck/README.md.'}
