// Presentation-only Chinese names for the pinned Human Atlas muscle set.
// Laterality is normalized separately so mirrored structures share one term.
const muscleTerms = Object.freeze({
  'abdominal part of pectoralis major': '胸大肌腹部',
  'abductor digiti minimi of foot': '足小趾展肌',
  'abductor digiti minimi of hand': '手小指展肌',
  'abductor hallucis': '拇展肌',
  'abductor pollicis brevis': '拇短展肌',
  'abductor pollicis longus': '拇长展肌',
  'acromial part of deltoid': '三角肌肩峰部',
  'adductor brevis': '短收肌',
  'adductor longus': '长收肌',
  'adductor magnus': '大收肌',
  'adductor minimus': '小收肌',
  'anconeus': '肘肌',
  'anterior papillary muscle of ventricle': '心室前乳头肌',
  'anterolateral head of lateral papillary muscle of ventricle': '心室外侧乳头肌前外侧头',
  'aryepiglotticus': '杓会厌肌',
  'ascending part of trapezius': '斜方肌升部',
  'brachialis': '肱肌',
  'brachioradialis': '肱桡肌',
  'cervical rotator': '颈旋转肌',
  'clavicular part of deltoid': '三角肌锁骨部',
  'clavicular part of pectoralis major': '胸大肌锁骨部',
  'coccygeus': '尾骨肌',
  'coracobrachialis': '喙肱肌',
  'descending part of trapezius': '斜方肌降部',
  'diaphragm': '膈肌',
  'digastric': '二腹肌',
  'extensor carpi radialis brevis': '桡侧腕短伸肌',
  'extensor carpi radialis longus': '桡侧腕长伸肌',
  'extensor carpi ulnaris': '尺侧腕伸肌',
  'extensor digiti minimi': '小指伸肌',
  'extensor digitorum': '指伸肌',
  'extensor digitorum longus': '趾长伸肌',
  'extensor hallucis brevis': '拇趾短伸肌',
  'extensor hallucis longus': '拇趾长伸肌',
  'extensor indicis': '食指伸肌',
  'extensor pollicis brevis': '拇短伸肌',
  'extensor pollicis longus': '拇长伸肌',
  'external anal sphincter': '肛门外括约肌',
  'external intercostal muscle': '肋间外肌',
  'external oblique': '腹外斜肌',
  'fibularis brevis': '腓骨短肌',
  'fibularis longus': '腓骨长肌',
  'fibularis tertius': '第三腓骨肌',
  'first lumbrical of foot': '足第一蚓状肌',
  'first plantar interosseous of foot': '足第一跖侧骨间肌',
  'flexor accessorius': '足底方肌',
  'flexor carpi radialis': '桡侧腕屈肌',
  'flexor digiti minimi brevis of foot': '足小趾短屈肌',
  'flexor digiti minimi brevis of hand': '手小指短屈肌',
  'flexor digitorum brevis': '趾短屈肌',
  'flexor digitorum longus': '趾长屈肌',
  'flexor digitorum profundus': '指深屈肌',
  'flexor digitorum superficialis': '指浅屈肌',
  'flexor hallucis longus': '拇趾长屈肌',
  'flexor pollicis brevis': '拇短屈肌',
  'flexor pollicis longus': '拇长屈肌',
  'fourth lumbrical of foot': '足第四蚓状肌',
  'gemellus inferior': '下孖肌',
  'gemellus superior': '上孖肌',
  'genioglossus': '颏舌肌',
  'geniohyoid': '颏舌骨肌',
  'gluteus maximus': '臀大肌',
  'gluteus medius': '臀中肌',
  'gluteus minimus': '臀小肌',
  'gracilis': '股薄肌',
  'humeral head of flexor carpi ulnaris': '尺侧腕屈肌肱骨头',
  'humeral head of pronator teres': '旋前圆肌肱骨头',
  'hyoglossus': '舌骨舌肌',
  'iliacus': '髂肌',
  'iliococcygeus': '髂尾肌',
  'iliocostalis cervicis': '颈髂肋肌',
  'iliocostalis lumborum': '腰髂肋肌',
  'iliocostalis thoracis': '胸髂肋肌',
  'inferior oblique': '下斜肌',
  'inferior oblique part of longus colli': '颈长肌下斜部',
  'inferior rectus': '下直肌',
  'infraspinatus muscle': '冈下肌',
  'innermost intercostal muscle': '肋间最内肌',
  'internal intercostal muscle': '肋间内肌',
  'interspinalis thoracis': '胸棘间肌',
  'lateral crico-arytenoid': '环杓侧肌',
  'lateral head of flexor hallucis brevis': '拇趾短屈肌外侧头',
  'lateral head of gastrocnemius': '腓肠肌外侧头',
  'lateral head of triceps brachii': '肱三头肌外侧头',
  'lateral lumbar intertransversarius': '腰外侧横突间肌',
  'lateral papillary muscle of ventricle': '心室外侧乳头肌',
  'lateral rectus': '外直肌',
  'levator palpebrae superioris': '上睑提肌',
  'levator scapulae': '肩胛提肌',
  'levator veli palatini': '腭帆提肌',
  'long head of biceps brachii': '肱二头肌长头',
  'long head of biceps femoris': '股二头肌长头',
  'long head of triceps brachii': '肱三头肌长头',
  'longissimus capitis': '头最长肌',
  'longissimus cervicis': '颈最长肌',
  'longissimus thoracis': '胸最长肌',
  'longus capitis': '头长肌',
  'lumbar rotator': '腰旋转肌',
  'medial head of flexor hallucis brevis': '拇趾短屈肌内侧头',
  'medial head of gastrocnemius': '腓肠肌内侧头',
  'medial head of triceps brachii': '肱三头肌内侧头',
  'medial lumbar intertransversarius': '腰内侧横突间肌',
  'medial rectus': '内直肌',
  'mylohyoid': '下颌舌骨肌',
  'oblique arytenoid': '杓斜肌',
  'oblique head of adductor hallucis': '拇趾收肌斜头',
  'oblique head of adductor pollicis': '拇收肌斜头',
  'oblique part of cricothyroid': '环甲肌斜部',
  'obliquus capitis inferior': '头下斜肌',
  'obliquus capitis superior': '头上斜肌',
  'obturator externus': '闭孔外肌',
  'obturator internus': '闭孔内肌',
  'omohyoid': '肩胛舌骨肌',
  'opponens digiti minimi of foot': '足小趾对跖肌',
  'opponens digiti minimi of hand': '手小指对掌肌',
  'opponens pollicis': '拇对掌肌',
  'palmaris longus': '掌长肌',
  'pectineus': '耻骨肌',
  'pectoralis minor': '胸小肌',
  'piriformis': '梨状肌',
  'plantaris': '跖肌',
  'platysma': '颈阔肌',
  'popliteus': '腘肌',
  'posterior crico-arytenoid': '环杓后肌',
  'posterior papillary muscle of ventricle': '心室后乳头肌',
  'pronator quadratus': '旋前方肌',
  'psoas major': '腰大肌',
  'pubococcygeus': '耻尾肌',
  'puborectalis': '耻骨直肠肌',
  'quadratus femoris': '股方肌',
  'rectus capitis anterior': '头前直肌',
  'rectus capitis lateralis': '头外侧直肌',
  'rectus capitis posterior major': '头后大直肌',
  'rectus capitis posterior minor': '头后小直肌',
  'rectus femoris': '股直肌',
  'rhomboid major': '大菱形肌',
  'rhomboid minor': '小菱形肌',
  'sartorius': '缝匠肌',
  'scalenus anterior': '前斜角肌',
  'scalenus medius': '中斜角肌',
  'scalenus posterior': '后斜角肌',
  'second lumbrical of foot': '足第二蚓状肌',
  'second plantar interosseous of foot': '足第二跖侧骨间肌',
  'semimembranosus': '半膜肌',
  'semispinalis capitis': '头半棘肌',
  'semispinalis cervicis': '颈半棘肌',
  'semispinalis thoracis': '胸半棘肌',
  'semitendinosus': '半腱肌',
  'septal papillary muscle of ventricle': '心室间隔乳头肌',
  'serratus anterior': '前锯肌',
  'serratus posterior inferior': '下后锯肌',
  'serratus posterior superior': '上后锯肌',
  'set of anterior cervical intertransversarii': '颈前横突间肌群',
  'set of dorsal interossei of hand': '手背侧骨间肌群',
  'set of interspinales cervicis': '颈棘间肌群',
  'set of interspinales lumborum': '腰棘间肌群',
  'set of levatores costarum breves': '短肋提肌群',
  'set of levatores costarum longi': '长肋提肌群',
  'set of lumbricals of hand': '手蚓状肌群',
  'set of palmar interossei of hand': '手掌侧骨间肌群',
  'set of posterior cervical intertransversarii': '颈后横突间肌群',
  'short head of biceps brachii': '肱二头肌短头',
  'short head of biceps femoris': '股二头肌短头',
  'soleus': '比目鱼肌',
  'spinal part of deltoid': '三角肌肩胛冈部',
  'spinalis': '棘肌',
  'spinalis thoracis': '胸棘肌',
  'splenius capitis': '头夹肌',
  'splenius cervicis': '颈夹肌',
  'sternocleidomastoid': '胸锁乳突肌',
  'sternocostal part of pectoralis major': '胸大肌胸肋部',
  'sternohyoid': '胸骨舌骨肌',
  'sternothyroid': '胸骨甲状肌',
  'straight part of cricothyroid': '环甲肌直部',
  'stylohyoid': '茎突舌骨肌',
  'subclavius': '锁骨下肌',
  'subscapularis': '肩胛下肌',
  'superficial head of flexor pollicis brevis': '拇短屈肌浅头',
  'superior oblique': '上斜肌',
  'superior oblique part of longus colli': '颈长肌上斜部',
  'superior rectus': '上直肌',
  'supinator': '旋后肌',
  'supraspinatus': '冈上肌',
  'tensor veli palatini': '腭帆张肌',
  'teres major': '大圆肌',
  'teres minor': '小圆肌',
  'third lumbrical of foot': '足第三蚓状肌',
  'third plantar interosseous of foot': '足第三跖侧骨间肌',
  'thoracic rotator': '胸旋转肌',
  'thyro-arytenoid': '甲杓肌',
  'thyrohyoid': '甲状舌骨肌',
  'tibialis anterior': '胫骨前肌',
  'tibialis posterior': '胫骨后肌',
  'transverse arytenoid': '杓横肌',
  'transverse head of adductor hallucis': '拇趾收肌横头',
  'transverse head of adductor pollicis': '拇收肌横头',
  'transverse part of trapezius': '斜方肌横部',
  'transversus thoracis': '胸横肌',
  'ulnar head of flexor carpi ulnaris': '尺侧腕屈肌尺骨头',
  'ulnar head of pronator teres': '旋前圆肌尺骨头',
  'uvular muscle': '悬雍垂肌',
  'vastus intermedius': '中间广肌',
  'vastus lateralis': '外侧广肌',
  'vastus medialis': '内侧广肌',
  'vertical intermediate part of longus colli': '颈长肌垂直中间部',
  'vocalis': '声带肌',
});

export function normalizeMuscleName(canonicalName) {
  return String(canonicalName || '').toLowerCase().replace(/\b(?:left|right)\b/g, '').replace(/\s+/g, ' ').trim();
}

export function hasChineseMuscleName(canonicalName) {
  return Object.hasOwn(muscleTerms, normalizeMuscleName(canonicalName));
}

export function muscleNameZh(canonicalName) {
  const source = String(canonicalName || '');
  const term = muscleTerms[normalizeMuscleName(source)] || '肌肉结构';
  const side = /\bleft\b/i.test(source) ? '左侧' : /\bright\b/i.test(source) ? '右侧' : '';
  return side + term;
}
