import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import { join } from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const moon = process.env.MOON ?? join(process.env.USERPROFILE ?? '', '.moon', 'bin', 'moon.exe');
if (!existsSync(moon)) throw new Error(`MoonBit compiler not found: ${moon}`);

const build = spawnSync(moon, ['build', '--target', 'js', 'moonbit/core'], { cwd: root, stdio: 'inherit' });
if (build.status !== 0) process.exit(build.status ?? 1);

const bundle = await readFile(join(root, '_build/js/debug/build/core/core.js'), 'utf8');
const htmlPath = join(root, 'index.html');
const html = await readFile(htmlPath, 'utf8');
const start = '<!-- MOONBIT_CORE_START -->';
const end = '<!-- MOONBIT_CORE_END -->';
const generated = `${start}\n<script>/* Generated by npm run build from moonbit/core. */\n${bundle}</script>\n${end}`;
if (!html.includes(start) || !html.includes(end)) throw new Error('Missing MoonBit generated-output markers in index.html.');
const updated = html.replace(new RegExp(`${start}[\\s\\S]*?${end}`), generated);
await writeFile(htmlPath, updated);
