import { readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { runMoon, verifyMoonVersion } from './moon-toolchain.mjs';

const root = fileURLToPath(new URL('..', import.meta.url));
const start = '<!-- MOONBIT_CORE_START -->';
const end = '<!-- MOONBIT_CORE_END -->';
function oneMarker(html, marker) { return html.split(marker).length - 1 === 1; }

try {
  verifyMoonVersion({ cwd: root });
  runMoon(['build', '--target', 'js', 'moonbit/core'], { cwd: root });
  const bundle = await readFile(join(root, '_build/js/debug/build/core/core.js'), 'utf8');
  const htmlPath = join(root, 'index.html');
  const html = await readFile(htmlPath, 'utf8');
  if (!oneMarker(html, start) || !oneMarker(html, end) || html.indexOf(start) > html.indexOf(end)) throw new Error('Expected exactly one ordered pair of MoonBit generated-output markers in index.html.');
  const generated = `${start}\n<script>/* Generated by npm run build from moonbit/core. */\n${bundle}</script>\n${end}`;
  const updated = html.slice(0, html.indexOf(start)) + generated + html.slice(html.indexOf(end) + end.length);
  await writeFile(htmlPath, updated);
} catch (error) {
  console.error(error.message);
  process.exitCode = 1;
}
