import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const directory = join(root, 'moonbit/core');
const files = (await readdir(directory)).filter((file) => file.endsWith('.mbt')).sort();
const production = files.filter((file) => !file.endsWith('_test.mbt'));
const tests = files.filter((file) => file.endsWith('_test.mbt'));
const effectiveLines = (source) => source.split(/\r?\n/).filter((line) => {
  const trimmed = line.trim();
  return trimmed && !trimmed.startsWith('///') && !trimmed.startsWith('//');
}).length;
const sources = Object.fromEntries(await Promise.all(files.map(async (file) => [file, await readFile(join(directory, file), 'utf8')])));
const total = (selected) => selected.reduce((sum, file) => sum + effectiveLines(sources[file]), 0);
const exports = production.reduce((sum, file) => sum + [...sources[file].matchAll(/\bpub\s+fn\s+\w+/g)].length, 0);
const testCount = tests.reduce((sum, file) => sum + [...sources[file].matchAll(/\btest\s+"/g)].length, 0);
const stats = Object.freeze({ productionFiles: production.length, productionEffectiveLoc: total(production), testFiles: tests.length, testEffectiveLoc: total(tests), exports, tests: testCount });
const text = [
  `MoonBit production files: ${stats.productionFiles}`,
  `MoonBit production effective LOC: ${stats.productionEffectiveLoc}`,
  `MoonBit test files: ${stats.testFiles}`,
  `MoonBit test effective LOC: ${stats.testEffectiveLoc}`,
  `MoonBit exports: ${stats.exports}`,
  `MoonBit tests: ${stats.tests}`,
].join('\n');
const markdown = `# MoonBit engine baseline\n\nThis report is generated by \`npm run moonbit:stats -- --write docs/MOONBIT_ENGINE_BASELINE.md\`. Effective LOC excludes blank and comment-only lines.\n\n\`\`\`text\n${text}\n\`\`\`\n`;

if (process.argv[2] === '--write' && process.argv[3]) await writeFile(resolve(root, process.argv[3]), markdown);
console.log(text);
