import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(fileURLToPath(new URL('..', import.meta.url)));
const directory = join(root, 'moonbit');
async function collect(relative = '') {
  const entries = await readdir(join(directory, relative), { withFileTypes: true });
  const nested = await Promise.all(entries.map((entry) => {
    const path = relative ? `${relative}/${entry.name}` : entry.name;
    return entry.isDirectory() ? collect(path) : entry.name.endsWith('.mbt') ? [path] : [];
  }));
  return nested.flat().sort();
}
const files = await collect();
const isTest = (file) => /_(?:wb)?test\.mbt$/.test(file);
const examples = files.filter((file) => file.startsWith('examples/'));
const production = files.filter((file) => !isTest(file) && !examples.includes(file));
const tests = files.filter(isTest);
const effectiveLines = (source) => source.split(/\r?\n/).filter((line) => {
  const trimmed = line.trim();
  return trimmed && !trimmed.startsWith('///') && !trimmed.startsWith('//');
}).length;
const sources = Object.fromEntries(await Promise.all(files.map(async (file) => [file, await readFile(join(directory, file), 'utf8')])));
const total = (selected) => selected.reduce((sum, file) => sum + effectiveLines(sources[file]), 0);
const exports = production.reduce((sum, file) => sum + [...sources[file].matchAll(/\bpub\s+fn\s+\w+/g)].length, 0);
const testCount = tests.reduce((sum, file) => sum + [...sources[file].matchAll(/\btest\s+"/g)].length, 0);
const stats = Object.freeze({ productionFiles: production.length, productionEffectiveLoc: total(production), testFiles: tests.length, testEffectiveLoc: total(tests), exports, tests: testCount });
const groups = [
  ['Reusable motion library', production.filter((file) => file.startsWith('motion/'))],
  ['Reusable anatomy terminology library', production.filter((file) => file.startsWith('anatomy/'))],
  ['Full-body environment and UI policies', production.filter((file) => /core\/(environment_scene|ui_feedback)\.mbt$/.test(file))],
  ['Browser wire adapters (motion, session, anatomy)', production.filter((file) => /core\/(full_body_motion|motion_session|anatomy_names)\.mbt$/.test(file))],
  ['Retained anatomy contracts', production.filter((file) => file.startsWith('core/') && !/\/(environment_scene|ui_feedback|full_body_motion|motion_session|anatomy_names)\.mbt$/.test(file))],
];
const breakdown = groups.map(([name, selected]) => ({ name, files: selected.length, effectiveLoc: total(selected) }));
const text = [
  `MoonBit production files: ${stats.productionFiles}`,
  `MoonBit production effective LOC: ${stats.productionEffectiveLoc}`,
  `MoonBit test files: ${stats.testFiles}`,
  `MoonBit test effective LOC: ${stats.testEffectiveLoc}`,
  `MoonBit public function declarations (including methods and adapters): ${stats.exports}`,
  `MoonBit tests: ${stats.tests}`,
  `MoonBit example effective LOC (excluded from production): ${total(examples)}`,
  ...breakdown.map((group) => `${group.name}: ${group.effectiveLoc} effective LOC (${group.files} files)`),
].join('\n');
const markdown = `# MoonBit engine baseline\n\nGenerated by \`npm run moonbit:stats -- --write docs/MOONBIT_ENGINE_BASELINE.md\`. Counts all authored packages under moonbit/. Blank/comment-only lines, generated JS/interfaces and examples are excluded from production LOC. Public function declarations include typed methods and compatibility wrappers; this is not a count of distinct product capabilities or foreign exports. Retained anatomy contracts are not an active neck page. LOC is a size measurement, not an eligibility score.\n\n\`\`\`text\n${text}\n\`\`\`\n`;

if (process.argv[2] === '--write' && process.argv[3]) await writeFile(resolve(root, process.argv[3]), markdown);
if (process.argv[2] === '--check') {
  const actual = await readFile(join(root, 'docs/MOONBIT_ENGINE_BASELINE.md'), 'utf8');
  if (actual.replace(/\r\n/g, '\n') !== markdown) throw Error('MoonBit baseline is stale. Run npm run moonbit:stats -- --write docs/MOONBIT_ENGINE_BASELINE.md.');
}
console.log(process.argv.includes('--json') ? JSON.stringify({ ...stats, exampleEffectiveLoc: total(examples), breakdown }, null, 2) : text);
